### ISSUE TITLE
Error with multiple rte css files

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3_encore#127]
It is possible to load multiple CSS files for the editor by using

```yaml
editor:
  config:
    contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css"]
```

this breaks with the exception
```
str_starts_with(): Argument #1 ($haystack) must be of type string, array given
```
