### ISSUE TITLE
Setting CSS for RTE does not work without buildName

### ISSUE THREAD

**Issue by rvock** [sabbelasichon/typo3_encore#131]
When the CSS for the RTE is set without a build name, the CSS is not correctly set.
This issue is a regression which was introduced with the fix for #127 in a2a1ff355aa79010b96fb7ad731c0d84f9234d48

```
# works
editor:
  config:
    contentsCss: "typo3_encore:_default:rte"

# does not work
editor:
  config:
    contentsCss: "typo3_encore:rte"
```

This issue is a result of these lines:
[RichtextEncoreConfiguration.php#L72-L75](https://github.com/sabbelasichon/typo3_encore/blob/master/Classes/Form/FormDataProvider/RichtextEncoreConfiguration.php#L72-L75)
